### ISSUE TITLE
Layed Display on <gridmaps.org/layers=G> Is Not consistent

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/openstreetmap-website#5]
The gridmaps.org main page is inconsistent and a little buggy with the overlay display.

For example, when the <i>Grid Data</i> layer is toggled like below, we do not see a display of grid information as expected.
![image](https://cloud.githubusercontent.com/assets/1178209/5149668/2483d168-7199-11e4-9875-b1922c926c99.png)

However, if we instead toggle on the <i> Map Data</i> layer like below, we then see the grid line data as we expected in the above case.
![image](https://cloud.githubusercontent.com/assets/1178209/5149704/75c23808-7199-11e4-81ac-cde33c621467.png)

**Comment by chrisnatali** [comment]
Just getting around to this.  Was resolved a while ago.
