### ISSUE TITLE
Differentiate Between Admin and Member user Accounts

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/openstreetmap-website#6]
KEDCO power user of gridmaps, Abdul-Hakeem Shaibu posed the following comment regarding account management of different users on the system: 
><i>I'm wondering if a managed activation method can be employed for gridmaps i.e. if someone registers, rather than activate using a link sent to provided email, an admin or moderator for the server (gridmaps.org) would be the one to activate the registered account.

>I fear that now that we've trained more staff and they are aware of the server and have the url, to avoid unauthorized staff from obtaining an acivated account and uploading or messing up data on the server, I think we ought to ensure a managed activation is employed.

>So what you think, would that be possible?﻿</i>

It seems reasonable to have a way to manage different account types on gridmaps.org. 

Also, we may want to even think about managing different groups delineated by regions... For example, the 'Kano Electricity Distribution Company' may have different users and even access privileges than the 'Benin Electricity Distribution Company Plc'.

**Comment by chrisnatali** [comment]
This is a great idea, though it's not in the scope of this particular fork.
